# Generated by Django 5.0.6 on 2025-05-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_default_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporatebylawsrequest',
            name='member_names',
        ),
        migrations.AddField(
            model_name='corporatebylawsrequest',
            name='authorized_shares',
            field=models.IntegerField(blank=True, help_text='Total number of authorized shares', null=True, verbose_name='Authorized Shares'),
        ),
        migrations.AddField(
            model_name='corporatebylawsrequest',
            name='board_of_directors',
            field=models.TextField(blank=True, help_text='List of board members with their positions', null=True, verbose_name='Board of Directors'),
        ),
        migrations.AddField(
            model_name='corporatebylawsrequest',
            name='corporate_officers',
            field=models.TextField(blank=True, help_text='List of corporate officers with their titles', null=True, verbose_name='Corporate Officers'),
        ),
        migrations.AddField(
            model_name='corporatebylawsrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='corporatebylawsrequest',
            name='par_value_per_share',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Par value per share', max_digits=10, null=True, verbose_name='Par Value Per Share'),
        ),
        migrations.AddField(
            model_name='corporatebylawsrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='compliancerequest',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('PAID', 'Paid'), ('FULLFILLED', 'Fullfilled')], default='IN_PROGRESS', max_length=20),
        ),
    ]
