# Generated by Django 5.0.6 on 2025-05-27 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_corporatebylawsrequest_member_names_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliancerequest',
            name='certificate_existence_request',
        ),
        migrations.RemoveField(
            model_name='compliancerequest',
            name='corporate_bylaws_request',
        ),
        migrations.RemoveField(
            model_name='compliancerequest',
            name='federal_ein_request',
        ),
        migrations.RemoveField(
            model_name='compliancerequest',
            name='labor_law_poster_request',
        ),
        migrations.RemoveField(
            model_name='compliancerequest',
            name='operating_agreement_request',
        ),
        migrations.RemoveField(
            model_name='corporatebylawsrequest',
            name='authorized_shares',
        ),
        migrations.RemoveField(
            model_name='corporatebylawsrequest',
            name='board_of_directors',
        ),
        migrations.RemoveField(
            model_name='corporatebylawsrequest',
            name='corporate_officers',
        ),
        migrations.RemoveField(
            model_name='corporatebylawsrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='corporatebylawsrequest',
            name='par_value_per_share',
        ),
        migrations.RemoveField(
            model_name='corporatebylawsrequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='certificateexistencerequest',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificateexistencerequest',
            name='business_reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificateexistencerequest',
            name='compliance_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_existence_request', to='core.compliancerequest'),
        ),
        migrations.AddField(
            model_name='certificateexistencerequest',
            name='file_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificateexistencerequest',
            name='other_reason_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificateexistencerequest',
            name='purpose_of_request',
            field=models.CharField(blank=True, choices=[('OPEN_BANKING_ACCOUNT', 'Open a bank account'), ('BUSINESS_LOAN', 'Business loan'), ('BUSINESS_CONTRACT', 'Business contract'), ('BUSINESS_LISCENSE', 'Business liscense'), ('OTHER_REASON', 'Other reason')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificateexistencerequest',
            name='requestor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='certificateexistencerequest',
            name='requestor_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificateexistencerequest',
            name='requestor_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificateexistencerequest',
            name='requestor_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='corporatebylawsrequest',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corporatebylawsrequest',
            name='business_reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='corporatebylawsrequest',
            name='compliance_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corporate_bylaws_request', to='core.compliancerequest'),
        ),
        migrations.AddField(
            model_name='corporatebylawsrequest',
            name='member_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporatebylawsrequest',
            name='other_reason_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corporatebylawsrequest',
            name='purpose_of_request',
            field=models.CharField(blank=True, choices=[('OPEN_BANKING_ACCOUNT', 'Open a bank account'), ('BUSINESS_LOAN', 'Business loan'), ('BUSINESS_CONTRACT', 'Business contract'), ('BUSINESS_LISCENSE', 'Business liscense'), ('OTHER_REASON', 'Other reason')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corporatebylawsrequest',
            name='requestor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='corporatebylawsrequest',
            name='requestor_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='corporatebylawsrequest',
            name='requestor_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='corporatebylawsrequest',
            name='requestor_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='federaleinrequest',
            name='compliance_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='federal_ein_request', to='core.compliancerequest'),
        ),
        migrations.AddField(
            model_name='federaleinrequest',
            name='members_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of members'),
        ),
        migrations.AddField(
            model_name='laborlawposterrequest',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laborlawposterrequest',
            name='business_reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laborlawposterrequest',
            name='compliance_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_law_poster_request', to='core.compliancerequest'),
        ),
        migrations.AddField(
            model_name='laborlawposterrequest',
            name='requestor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='laborlawposterrequest',
            name='requestor_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laborlawposterrequest',
            name='requestor_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laborlawposterrequest',
            name='requestor_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='operatingagreementrequest',
            name='captial_contributions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operatingagreementrequest',
            name='compliance_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operating_agreement_request', to='core.compliancerequest'),
        ),
        migrations.AddField(
            model_name='operatingagreementrequest',
            name='management_structure',
            field=models.TextField(blank=True, choices=[('MEMBER_MANAGED', 'Member Managed'), ('MANAGER_MANAGED', 'Manager Managed')], null=True),
        ),
        migrations.AddField(
            model_name='operatingagreementrequest',
            name='ownership_precentages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operatingagreementrequest',
            name='profit_distribution_method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compliancerequest',
            name='request_type',
            field=models.CharField(choices=[('ANNUAL_REPORT', 'Annual Report'), ('OPERATING_AGREEMENT', 'Operating Agreement'), ('CORPORATE_BYLAWS', 'Corporate Bylaws'), ('FEDERAL_EIN', 'Federal EIN Application'), ('LABOR_LAW_POSTER', 'Labor Law Poster'), ('CERTIFICATE_EXISTENCE', 'Certificate of Existence')], max_length=25),
        ),
        migrations.AlterField(
            model_name='compliancerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PAYMENT_PENDING', 'Payment Pending')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='federaleinrequest',
            name='llc_accounting_year_closing_month',
            field=models.CharField(blank=True, choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'April'), ('MAY', 'May'), ('JUNE', 'June'), ('JULY', 'July'), ('AUGUST', 'August'), ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'), ('DECEMBER', 'December')], max_length=20, null=True, verbose_name='Closing month of accounting year'),
        ),
        migrations.AlterField(
            model_name='federaleinrequest',
            name='primary_business_activity',
            field=models.CharField(blank=True, choices=[('ACCOMMODATION_FOOD', 'Accommodation & Food Services'), ('CONSTRUCTION', 'Construction'), ('REAL_ESTATE', 'Real Estate, Rental & Leasing'), ('RETAIL', 'Retail'), ('MANUFACTURING', 'Manufacturing'), ('HEALTHCARE_SOCIAL', 'Health Care & Social Assistance'), ('FINANCE_INSURANCE', 'Finance & Insurance'), ('TRANSPORTATION_WAREHOUSING', 'Transportation & Warehousing'), ('WHOLESALE_TRADE', 'Wholesale Trade'), ('OTHER_SERVICES', 'Other Services (except Public Administration)')], max_length=100, null=True, verbose_name='Primary Business Activity'),
        ),
    ]
