# Generated by Django 5.0.6 on 2025-05-28 02:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_compliancerequest_certificate_existence_request_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='business',
            new_name='core_busine_referen_1d954f_idx',
            old_name='core_busine_referen_85d542_idx',
        ),
        migrations.RemoveField(
            model_name='business',
            name='id',
        ),
        migrations.AlterField(
            model_name='business',
            name='reference_id',
            field=models.CharField(default=core.models.generate_reference_id, help_text='The unique identifier for the business entity.', max_length=255, primary_key=True, serialize=False, verbose_name='Reference ID'),
        ),
    ]
