from django.db import migrations
from datetime import date, timedelta

def load_test_businesses(apps, schema_editor):
    Business = apps.get_model('core', 'Business')
    
    # Create test businesses
    businesses = [
        {
            'name': 'Acme Technologies LLC',
            'business_type': 'LLC',
            'address': '123 Main Street',
            'address2': 'Suite 100',
            'city': 'Raleigh',
            'state_code': 'NC',
            'zip_code': '27601',
            'registered_agent': 'John Smith',
            'date_formed': date(2024, 1, 15),
            'last_filing_date': date(2024, 1, 15),
            'status': 'ACTIVE',
            'is_new': True,
            'missing_filing': False
        },
        {
            'name': 'Global Solutions Corp',
            'business_type': 'CORP',
            'address': '456 Business Park',
            'address2': None,
            'city': 'Charlotte',
            'state_code': 'NC',
            'zip_code': '28202',
            'registered_agent': 'Sarah Johnson',
            'date_formed': date(2023, 6, 1),
            'last_filing_date': date(2024, 1, 1),
            'status': 'ACTIVE',
            'is_new': False,
            'missing_filing': False
        },
        {
            'name': 'Innovative Services LLC',
            'business_type': 'LLC',
            'address': '789 Tech Boulevard',
            'address2': 'Unit 200',
            'city': 'Durham',
            'state_code': 'NC',
            'zip_code': '27701',
            'registered_agent': 'Michael Brown',
            'date_formed': date(2023, 12, 1),
            'last_filing_date': date(2023, 12, 1),
            'status': 'ACTIVE',
            'is_new': True,
            'missing_filing': True
        },
        {
            'name': 'Premier Consulting Corp',
            'business_type': 'CORP',
            'address': '321 Corporate Center',
            'address2': 'Floor 15',
            'city': 'Greensboro',
            'state_code': 'NC',
            'zip_code': '27401',
            'registered_agent': 'Emily Davis',
            'date_formed': date(2023, 3, 15),
            'last_filing_date': date(2023, 12, 31),
            'status': 'ACTIVE',
            'is_new': False,
            'missing_filing': True
        },
        {
            'name': 'Elite Business Solutions LLC',
            'business_type': 'LLC',
            'address': '555 Enterprise Way',
            'address2': None,
            'city': 'Winston-Salem',
            'state_code': 'NC',
            'zip_code': '27101',
            'registered_agent': 'David Wilson',
            'date_formed': date(2024, 2, 1),
            'last_filing_date': date(2024, 2, 1),
            'status': 'ACTIVE',
            'is_new': True,
            'missing_filing': False
        }
    ]

    for business_data in businesses:
        # Create business without reference_id to let the model handle it
        business = Business.objects.create(**business_data)
        # The reference_id will be automatically generated by the model's default

def remove_test_businesses(apps, schema_editor):
    Business = apps.get_model('core', 'Business')
    Business.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_rename_core_busine_referen_85d542_idx_core_busine_referen_1d954f_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(load_test_businesses, remove_test_businesses),
    ] 