# Generated by Django 5.0.6 on 2025-05-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_load_test_businesses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatingagreementrequest',
            old_name='captial_contributions',
            new_name='capital_contributions',
        ),
        migrations.RenameField(
            model_name='operatingagreementrequest',
            old_name='ownership_precentages',
            new_name='ownership_percentages',
        ),
        migrations.RenameField(
            model_name='operatingagreementrequest',
            old_name='profit_distribution_method',
            new_name='profit_distribution',
        ),
        migrations.AlterField(
            model_name='operatingagreementrequest',
            name='management_structure',
            field=models.CharField(blank=True, choices=[('MEMBER_MANAGED', 'Member Managed'), ('MANAGER_MANAGED', 'Manager Managed')], max_length=20, null=True),
        ),
    ]
