# Generated by Django 5.0.6 on 2025-05-30 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_captial_contributions_operatingagreementrequest_capital_contributions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='federaleinrequest',
            name='llc_members_count',
        ),
    ]
