# Generated by Django 5.0.6 on 2025-05-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_llc_members_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
    ]
