# Generated by Django 5.0.6 on 2025-05-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_compliancerequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporatebylawsrequest',
            name='member_names',
        ),
        migrations.AddField(
            model_name='corporatebylawsrequest',
            name='authorized_shares',
            field=models.IntegerField(blank=True, help_text='Total number of authorized shares', null=True),
        ),
        migrations.AddField(
            model_name='corporatebylawsrequest',
            name='board_of_directors',
            field=models.TextField(blank=True, help_text='List of board members with their positions', null=True),
        ),
        migrations.AddField(
            model_name='corporatebylawsrequest',
            name='corporate_officers',
            field=models.TextField(blank=True, help_text='List of corporate officers with their titles', null=True),
        ),
        migrations.AddField(
            model_name='corporatebylawsrequest',
            name='par_value_per_share',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Par value per share', max_digits=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='compliancerequest',
            unique_together={('business', 'request_type')},
        ),
    ]
