# Generated by Django 5.0.6 on 2025-05-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_corporatebylawsrequest_member_names_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporatebylawsrequest',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='corporatebylawsrequest',
            name='business_reference_id',
        ),
        migrations.RemoveField(
            model_name='corporatebylawsrequest',
            name='other_reason_text',
        ),
        migrations.RemoveField(
            model_name='corporatebylawsrequest',
            name='purpose_of_request',
        ),
        migrations.RemoveField(
            model_name='corporatebylawsrequest',
            name='requestor_email',
        ),
        migrations.RemoveField(
            model_name='corporatebylawsrequest',
            name='requestor_first_name',
        ),
        migrations.RemoveField(
            model_name='corporatebylawsrequest',
            name='requestor_last_name',
        ),
        migrations.RemoveField(
            model_name='corporatebylawsrequest',
            name='requestor_phone_number',
        ),
        migrations.AddField(
            model_name='compliancerequest',
            name='order_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Order Reference Number'),
        ),
    ]
