# Generated by Django 5.0.6 on 2025-05-30 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_order_reference_number'),
        ('core', '0011_remove_corporatebylawsrequest_business_name_and_more'),
    ]

    operations = [
    ]
