# Generated by Django 5.0.6 on 2025-05-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20250530_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliancerequest',
            name='order_reference',
        ),
        migrations.AddField(
            model_name='compliancerequest',
            name='unlimited_amendments',
            field=models.BooleanField(default=False, help_text='If true, the client has selected unlimited amendments add-on.'),
        ),
    ]
